### ISSUE TITLE
Async Image Generation

### ISSUE THREAD

**Issue by Richie94** [2xlink/DrawPhone#35]
For having a faster experience between finishing drawing and seeing the results, the saving of the image should be async and just be awaited in the end when the download button is present.

**Comment by 2xlink** [comment]
Hello Richie,
what do you mean with "saving of the image"? If you mean the "Download results" button at the end of the results page, the code for image generation and download should be triggered only if you click on it, meaning it is already async.

**Comment by Richie94** [comment]
Okay, i though that the long part between finishing the game by writing the last guesses and presenting the results comes from the generation of the data-history-dump which is i assumed the picture-creation.

**Comment by 2xlink** [comment]
I *think* it's because the whole history object is serialized on server side, sent to every client and then deserialized on the client. The drawings currently are actually JSON objects, like svg, which can become huge if many players are present (and many things are drawn).
Converting the svgs to jpegs before sending them is on my to-do list, but I did not find time to implement that yet …

**Comment by 2xlink** [comment]
I just pushed an update, which should speed things up a bit. You can try it next time! :)

**Comment by Richie94** [comment]
Great, I'll check soon.

**Comment by Richie94** [comment]
Tried with 8 players, soo much better. Good job.
